# Generated by Django 5.0 on 2023-12-25 23:18

import django.db.models.manager
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50, verbose_name="Nome do pedido")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=9, verbose_name="Valor")),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("physical_product", "Produto fisico"),
                            ("book", "Livro"),
                            ("member_association", "Associação de membro"),
                            ("upgrade_member_association", "Updgrade de associação de membro"),
                            ("video", "Video"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
            },
            managers=[
                ("objects_post_payment", django.db.models.manager.Manager()),
            ],
        ),
    ]
